#!/usr/bin/php
<?php declare(strict_types=1);

namespace Xeros;

use Exception;

include 'bootstrap.php';

$block = new Block();
$miner = new Miner();
$pow = new Pow();
$nonce = 0;

$candidateBlock = $block->genesis();
$blockHeader = $block->generateBlockHeader($candidateBlock);

while (1) {
    try {
        $result = $miner->mineBlock($blockHeader, $candidateBlock['difficulty'], 1, $nonce, false);
        if ($result['result'] === true) {
            break;
        }

        $nonce = $result['nonce'];

    } catch (Exception $e) {
        echo $e->getMessage(), "\n";
        exit(1);
    }
}

$candidateBlock['hash'] = $result['hash'];
$candidateBlock['nonce'] = dechex($result['nonce']);

$reason = $block->validateFullBlock($candidateBlock);

print_r($candidateBlock);

echo "\nFound in " . number_format($result['hashes'], 0) . " Hashes\n";
echo "Nonce: {$result['nonce']}\n";
echo "Hash: {$result['hash']}\n\n";

$verified = $pow->verifyPow($result['hash'], $blockHeader, dechex($result['nonce']));
if ($verified) {
    echo "--> Hash verified\n";
} else {
    echo "--X Hash mismatch\n";
}

